{% set version = "3.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pairwisecomparisons
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pairwiseComparisons_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pairwiseComparisons/pairwiseComparisons_{{ version }}.tar.gz
  sha256: 39848eb5b5c1a495fa625e4a6e7fdb1e79163c2120976dbebb176173eccdc022

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-pmcmrplus
    - r-wrs2 >=1.1_3
    - r-dplyr
    - r-insight >=0.14.5
    - r-parameters >=0.15.0
    - r-purrr
    - r-rlang
    - r-statsexpressions >=1.2.0
  run:
    - r-base
    - r-pmcmrplus
    - r-wrs2 >=1.1_3
    - r-dplyr
    - r-insight >=0.14.5
    - r-parameters >=0.15.0
    - r-purrr
    - r-rlang
    - r-statsexpressions >=1.2.0

test:
  commands:
    - $R -e "library('pairwiseComparisons')"           # [not win]
    - "\"%R%\" -e \"library('pairwiseComparisons')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/pairwiseComparisons/, https://github.com/IndrajeetPatil/pairwiseComparisons
  license: GPL-3.0-only
  summary: "Multiple pairwise comparison tests on tidy data for one-way analysis of variance for both between-subjects and within-subjects designs. Currently, it supports only the most common types of statistical analyses and tests: parametric (Welch's and Student's t-test), nonparametric (Durbin-Conover test and Dwass-Steel-Crichtlow-Fligner\
    \ test), robust (Yuen’s trimmed means test)."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: pairwiseComparisons
# Title: Multiple Pairwise Comparison Tests
# Version: 0.2.5
# Authors@R: person(given = "Indrajeet", family = "Patil", role = c("cre", "aut", "ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Multiple pairwise comparison tests on tidy data for one-way analysis of variance for both between-subjects and within-subjects designs. Currently, it supports only the most common types of statistical analyses and tests: parametric (Welch's and Student's t-test), nonparametric (Durbin-Conover test and Dwass-Steel-Crichtlow-Fligner test), robust (Yuens trimmed means test).
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/pairwiseComparisons/, https://github.com/IndrajeetPatil/pairwiseComparisons
# BugReports: https://github.com/IndrajeetPatil/pairwiseComparisons/issues
# Depends: R (>= 3.5.0)
# Imports: dplyr (>= 0.8.3), forcats (>= 0.4.0), ipmisc (>= 1.0.0), jmv (>= 1.0.8), purrr (>= 0.3.3), rlang (>= 0.4.2), stats, tibble (>= 2.1.3), tidyr (>= 1.0.0), utils, WRS2 (>= 1.0-0)
# Suggests: ggplot2, knitr, rmarkdown, spelling, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.0.2.9000
# NeedsCompilation: no
# Packaged: 2020-02-11 10:01:14 UTC; inp099
# Author: Indrajeet Patil [cre, aut, ctb] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2020-02-11 10:50:05 UTC
