{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pairwisecomparisons
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pairwiseComparisons_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pairwiseComparisons/pairwiseComparisons_{{ version }}.tar.gz
  sha256: 713e28855312d9fe25991815df4f9cab28020aef932877230ef9aa1ff719cbc1

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-wrs2 >=1.0_0
    - r-broomextra >=0.0.5
    - r-crayon >=1.3.4
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-groupedstats >=0.0.9
    - r-jmv >=0.9.6.1
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0
  run:
    - r-base
    - r-wrs2 >=1.0_0
    - r-broomextra >=0.0.5
    - r-crayon >=1.3.4
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-groupedstats >=0.0.9
    - r-jmv >=0.9.6.1
    - r-purrr >=0.3.2
    - r-rlang >=0.4.0
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0

test:
  commands:
    - $R -e "library('pairwiseComparisons')"           # [not win]
    - "\"%R%\" -e \"library('pairwiseComparisons')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/pairwiseComparisons/, https://github.com/IndrajeetPatil/pairwiseComparisons
  license: GPL-3
  summary: "Multiple pairwise comparison tests for one-way analysis of variance for both between-subjects
    and within-subjects designs. Currently, it supports only the most common types of
    statistical analyses and tests: parametric (Welch's and Student's t-test), nonparametric
    (Durbin-Conover test and Dwass-Steel-Crichtlow-Fligner test), robust (Yuen\xE2\u20AC\u2122s
    trimmed means test)."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: pairwiseComparisons
# Title: Multiple Pairwise Comparison Tests
# Version: 0.1.1
# Authors@R:  person(given = "Indrajeet", family = "Patil", role = c("cre", "aut", "ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Multiple pairwise comparison tests for one-way analysis of variance for both between-subjects and within-subjects designs. Currently, it supports only the most common types of statistical analyses and tests: parametric (Welch's and Student's t-test), nonparametric (Durbin-Conover test and Dwass-Steel-Crichtlow-Fligner test), robust (YuenaTMs trimmed means test).
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/pairwiseComparisons/, https://github.com/IndrajeetPatil/pairwiseComparisons
# BugReports: https://github.com/IndrajeetPatil/pairwiseComparisons/issues
# Depends: R (>= 3.5.0)
# Imports: broomExtra (>= 0.0.5), crayon (>= 1.3.4), dplyr (>= 0.8.3), forcats (>= 0.4.0), groupedstats (>= 0.0.9), jmv (>= 0.9.6.1), purrr (>= 0.3.2), rlang (>= 0.4.0), stats, stringr (>= 1.4.0), tibble (>= 2.1.3), tidyr (>= 1.0.0), utils, WRS2 (>= 1.0-0)
# Suggests: ggplot2, knitr, rmarkdown, spelling, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.99.9000
# NeedsCompilation: no
# Packaged: 2019-09-17 08:30:30 UTC; inp099
# Author: Indrajeet Patil [cre, aut, ctb] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2019-09-17 09:20:02 UTC
