travis:
  secure:
    BINSTAR_TOKEN: HbPDE+hxSrOjuhEoWNvlEOlB3SocKofHhbJyDFEvdIeSU4TnGzwgDXukLLyoQw0Em8EPZ6Ax9sBu4IWCjM42YWFMgKlPra0X+EOx1bYAhaVUPae9Im9j+bZhD1L2TMEOVPdJBnSOdYHQ4PsvkcPj1c0GRqzBuzfezZRvm/aSVn1uQk9eyzufOzH7TTmqIC84d+xkFcHLP+UW2QAOkJcVHWWWso5gb98aQYPgooOMlTRPwW3UQtZdd7URl6gporogVrKvB7FvAZbgBPGAX1EX8VJm5F416LTcw1qa4gqkW223gaMSEn7T511tpC1yUGY+To5RYiNPVBtVwHVI4EeiZjww89FIk6OtQJxdjnnwfapJXQIQ4hT7YCF7R/MafQYLD+J1if4Frh586SeNAh/fIfK+osJSLe/TzYIPQC547t2tavx30gqm1CUzQ6y1GtjTcO/4Qf0mBMBJ310/G1tGOn5XdPsjB9emYahn741IbfFR+nGv59dG7tFHSYb88baDYjwDnUVMJuZBqWW5c3v+xPudciE8ujWT8Rgqglgb1TtdIleLIuGQUZHBSshP87/2v1n96cF8p2LWsApSGGIN1mAtZuH+GLwjCyj8w+OVrfvd7M2wpX7oaBMw2o8rXelZ7wGoEQhBPfjX5nBUWZylclXHoVzLLM5iF8yDjkrUAQI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
